### ISSUE TITLE
read_cats

### ISSUE THREAD

**Issue by AndreaOkeanos** [animaltags/tagtools_r#6]
Hi!

I have been using this package with the same tags for three years now, and a few days ago I updated the product with your latest version. However, I am currently unable to use the read_cats function after the recent update. It's giving me the following error:

```
C <- read_cats("file.csv", "NC")
_Error in strptime(x, format, tz = tz) : input string is too long                                                       
In addition: Warning messages:
1: The following named parsers don't match the column names: GPS (raw) 1 [raw], GPS (raw) 2 [raw] 
2: One or more parsing issues, call problems() on your data frame for details, e.g.:
  dat <- vroom(...)
  problems(dat)_ 
```
I couldn't find the older version of the package but I would love to try it again. 
Is the older version still available somewhere?

I could use some help.

Thank you,

Andrea Herguedas

**Comment by stacyderuiter** [comment]
Hi Andrea,  

Thanks for reaching out.

Can you let me know (if you have an idea) when the previous version of read_cats() (that worked for you) dated from? The function has not changed since last summer, and the changes last summer were only to rename variables (we had things called "T" and "F" which CRAN doesn't allow).

My other question is to clarify what you were doing when the error arose. It sounds like you are trying to read in the same exact tag data files that you _were_ able to read before -- not new tag records. If the problem has arisen with _new_ tag records that you have never read in before, then the problem could lie with the function OR with the CATS tag data format, so important to know for debugging. The error message you are getting kind of looks like the CATS datafile format could have changed, although it may also be changes to packages animaltags depends on, or maybe some other bug.

About a week ago I ran all our unit tests on the animaltags package and they passed, which suggests the function is still working at least on _our_ test/demo CATs data file. 

One thing I could do is to try to find and send you and "older" version of the function, but I'd prefer to figure out what is going on and fix the current one. To do that it might help if you are able to send me one of the data files you are having trouble with (it could be a truncated version with just a few rows of data, if it is large or if you prefer not to share your data). If you are willing to do that, probably don't post your data here publicly -- we can move the conversation to email -- I am sld33 at calvin.edu.

**Comment by stacyderuiter** [comment]
read_cats() has now been updated to deal better with the column names present in more recent CATS csv data files, and to convert the CATs standard NED axis orientation (for all triaxial sensors) to the NEU orientation expected by  the tagtools. (commit ff858942cf12f7f890d8974162bd8fc3b85ded41)
